version: '3'
services:
  cli:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: ${IMAGE}
    stdin_open: true
    tty: true
    depends_on:
      - db
  
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    restart: always
