version: '3'
services:
  cli:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: app_crud_python
    stdin_open: true
    tty: true
    depends_on:
      - db
  
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: always

volumes:
  db-data:
